version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
    volumes:
      - ./app:/home/app
      - ./docker/app:/home/docker
      - ./docker/etc/gunicorn.conf:/home/docker/etc/gunicorn.conf
      - ./docker/var/log/gunicorn:/var/log/gunicorn
    working_dir: /home/app
    entrypoint: "/bin/sh"
    command: "/home/docker/start-server.sh"
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/pgsql-data:/var/lib/postgresql/data
